### ISSUE TITLE
Option to prevent us from being added to channels access lists

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [anope/anope#317]
**Description**
Currently we have no option to prevent us from being added to access lists.  
This option could be named `NEVEROP`. 

**Why this would be useful**
This would prevent us from being added to access lists without being previously warned or consulted.
While this may seem strange, I don't like the fact that anyone can add me to the access list of a channel *just because* they can.

**Comment by PeGaSuS-Coder** [comment]
> Interesting, but "/ns set autoop OFF" don't do the job

No. The idea is to not be added to any access list without prior consent.
Atheme has this option as `NEVEROP` and even DALnet has their own version of it as `NOOP`.

**Comment by SadieCat** [comment]
Implemented in commit c3e95d8e2ec1a7d520db54b339277505243b5fc6.

**Comment by SadieCat** [comment]
Implemented in commit 3371941be5eb2d783a512d326f28165d101da6ee.
