### ISSUE TITLE
user account in access list

### ISSUE THREAD

**Issue by incorrigo** [anope/anope#323]
**Description**
when you add someone to chanserv access # list, it adds the account they are logged in as, but when you go to remove the access entry, it says *nick* doesn't exist if the account is not the same as the nickname they are using

**Steps to reproduce the issue:**

1.register 2 nicknames in 1 group
2.log into account using [the / a] nickname that isn't group nickname
3.registered channel owner add nickname from [2] to registered channel's access list
4. try and remove same nickname from same access list

**Describe the results you received:**
5. [chanserv]: error: [nickname] not found on [channel]'s access list

**Describe the results you expected:**
maps user's nickname to account nickname when adding a non-*!*@* entry to access list
maps user's nickname to account nickname when removing a non-*!*@* entry from access list

**Additional information you deem important (e.g. issue happens only occasionally):**
in any other case chanserv is good at knowing the difference between a mask and a registered nickname

**Output of `services --version`:**
[17:03] -chanserv- [non group nickname] not found on #channelname access list.
Anope 2.0.14

**Comment by SadieCat** [comment]
I think I see why this is happening. When we add a non-glob/channel entry the NickAlias is converted to the NickCore in `ChanAccess::SetMask` but we don't do the reverse when removing an entry.

**Comment by incorrigo** [comment]
i'm not sure how to apply this patch to my current services. i've always used the stable version and never installed things like third party modules &c. if you could tell me how to implement this patch i will do it and see if it works

**Comment by SadieCat** [comment]
If you installed the release from source you can use these commands in the root of your Anope source tree:

```sh
wget https://github.com/SadieCat/anope/commit/69a0f3bec2cfed1436385a41fe73b2a95f5bf64a.patch
patch -p1 < 69a0f3bec2cfed1436385a41fe73b2a95f5bf64a.patch
./Config -quick
cd build
make install
```

**Comment by SadieCat** [comment]
I've tested my patch for this a bunch and I think it should fix it so I've pushed it. Please comment if you find any issues with it.
