### ISSUE TITLE
Server operators can't confirm their account with a passcode

### ISSUE THREAD

**Issue by bugz8unny69** [anope/anope#324]
**Description**
When you `CONFIRM passcode`, Anope throws an error that `Nick passcode isn't registered`

**Steps to reproduce the issue:**

1. Register an account
2. Wait for E-Mail
3. Execute: `/msg NickServ CONFIRM passcode`

**Describe the results you received:**
`Nick passcode isn't registered`

**Describe the results you expected:**
`Nick example has been confirmed.`

**Additional information you deem important (e.g. issue happens only occasionally):**
The documentation states:

```
Syntax: CONFIRM passcode
This command is used by several commands as a way to confirm
changes made to your account.
```

However, the correct syntax it accepts is `/msg NickServ CONFIRM nick passcode`. Looks, like the documentation wasn't updated including with E-Mail examples in `services.conf`

**Output of `services --version`:**

`Anope-2.0.14 -- build #1, compiled 05:48:40 Oct 20 2023`

**Comment by SadieCat** [comment]
The syntax is actually `CONFIRM <passcode>` for regular users. I'm guessing you're a services oper with the `nickserv/confirm` privilege? I think you're encountering a weird edge case where oper autoconfirmation is messing with the confirmation of your own nick.

**Comment by SadieCat** [comment]
This should fix the issue and allow you to confirm your account normally. Would it be possible for you to test it?

https://github.com/anope/anope/compare/2.0...SadieCat:anope:2.0+confirm

**Comment by bugz8unny69** [comment]
Do you have a patch file that I can apply cleanly?  Using https://github.com/anope/anope/commit/9fc53199ade90a852998587f52e91d49a149fc21.patch fails to apply cleanly here. 

In the mean time, I will try to apply the changes manually.

**Comment by bugz8unny69** [comment]
Yes, works here in my testing.

**Comment by SadieCat** [comment]
Merged: https://github.com/anope/anope/commit/97fa6d84bcb70b3b87d3fd7cc14f3b2567ca4e11

Thanks for reporting!
