### ISSUE TITLE
Normal users can't see suspended channel related info

### ISSUE THREAD

**Issue by TehPeGaSuS** [anope/anope#325]
**Description**
If I understand [this option](https://github.com/anope/anope/blob/2.0/data/chanserv.example.conf#L1237) (and the comments above it), when a channel is suspend **ANY** user should be able to view that the channel is suspended, by who, reason, when and expiration date (if any).
Actually you can only see that info if identified to a nick (grouped or otherwise) that have oper privs on the network.

**Steps to reproduce the issue:**
1. Suspend a channel with `/chanserv suspend #channel +0 Suspended for internal reasons`
2. Do `/chanserv info #channel` as oper or identified to a nick (grouped or otherwise) that has oper privs on the network
3. You should be able to see that the channel is suspended, by who, reason, when and expiration date (if any)
4. Use another nickname that doesn't have oper privs on the network
5. Do `/chanserv info #channel`
6. You can't see any of the suspended related info

**Describe the results you received:**
Normal users can't see any info related to suspended channel(s)

**Describe the results you expected:**
If [this option](https://github.com/anope/anope/blob/2.0/data/chanserv.example.conf#L1237) isn't commented, any user should be able to see the info related to suspended channel(s)

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Output of `services --version`:**
Anope-2.0.15-git (g0715db7) -- build #1, compiled 09:47:31 Oct  6 2023, flags DG

**Comment by SadieCat** [comment]
It seems like that option is in the config but isn't actually implemented? Weird.
