### ISSUE TITLE
Customization of the mail module

### ISSUE THREAD

**Issue by DiamantTh** [anope/anope#328]
So one more request.

I would like to ask how the mail component is being modernized?
Because I have been asking myself for some time why it is not yet possible to send mails via smtp with forced authentication from mail/password and TLS?

Especially if you use an external service provider that is suitable for sending mails.

I would be happy to receive a statement from you.

Greetings from Bavaria.

**Comment by Adam-** [comment]
Anope sends mail via `sendmail` (or another compatible MTA) and it isn't its own SMTP client. You can configure sendmail to do TLS authentication.
