### ISSUE TITLE
Error with the modules m_httpd and m_proxyscan

### ISSUE THREAD

**Issue by cubarebota** [anope/anope#332]
**_Greetings to all. I already have Anope 2.1.0 installed, but when I run it I get this error in the terminal:_**

**M_HTTPD:** Unable to create HTTP server httpd/main: _Unable to epoll_ctl() fd -1 to epoll: Bad file descriptor_

Module **m_proxyscan** couldn't load due to configuration problems: m_proxyscan: _Unable to epoll_ctl() fd -1 to epoll: Bad file descriptor_

**Comment by SadieCat** [comment]
This has already been fixed in 2.1 Git and will be in the next release.
