### ISSUE TITLE
Read TLS certificate and keypair from confdir instead of runtime directory.

### ISSUE THREAD

**Issue by GTAXL** [anope/anope#349]
I run Anope 2.0.12 from Debian. I was scratching my head wondering where Anope reads the SSL cert/key from. Doing some digging with strace, it appears Anope reads it from the runtime directory the binary was executed in when you provide a relative path in the config, such as the default data/anope.key. I figured it would of been reading from confdir or dbdir directories. Reading from the runtime directory isn't package friendly or if using something like systemd. In this case it was reading relative in the /run/anope/ directory. To fix my issue I just used an absolute path in the config. I think it would make more sense and be package friendly to read relative from confdir or dbdir.

**Comment by Adam-** [comment]
Anope chdirs to the parent directory of the service's bin directory (so eg if the exeuctable is `/home/user/services/bin/services` it will chdir to `/home/user/services`) on startup, prior to reading the config. It doesn't read relative to the runtime directory the binary was executed in. The default config references paths to keys such as `data/anope.key`, and they work.

**Comment by GTAXL** [comment]
Sure, that's the behavior when Anope is compiled and ran from source. In this case the binary sits at `/usr/sbin/anope`. Where is it going to chdir to? I straced it and even called the binary from a different directory, and whatever directory I was in is where Anope attempted to read the relative path for the ssl cert/key. Looking at the systemd service unit, the runtime directory is /run/anope/ which the run directory is a common place to store pids. It respects absolute paths so it's a non-issue just something I discovered. But if you wish for Anope to be more package friendly, or maybe Anope might release their own .debs down the road, this behavior should probably change and it read from something like confdir. There really isn't a "services root" on a packaged install. All the directories are passed as flags to the binary on runtime.
`/usr/sbin/anope --confdir=/etc/anope --dbdir=/var/lib/anope/db --logdir=/var/log/anope --modulesdir=/usr/lib/anope --localedir=/usr/share/anope/locale`

**Comment by Adam-** [comment]
> In this case the binary sits at /usr/sbin/anope. Where is it going to chdir to?

I think it will chdir to `/usr`. If it isn't that might be a bug. You could breakpoint Anope::Init and find out.

If running Anope from source reads the keys from the installation base and not from the runtime directory, as you have acknowledged, then describing your issue as `Read TLS certificate and keypair from confdir instead of runtime directory` is disingenuous at best. This *is* what it does, and running from source is the main supported way people run Anope.

If you can figure out a way to improve the current way it works in a way that doesn't break the existing installs, I am open to that. Nothing comes to mind immediately.

**Comment by GTAXL** [comment]
> You could breakpoint Anope::Init and find out.

I'm not sure how I would do that.

> If you can figure out a way to improve the current way it works in a way that doesn't break the existing installs, I am open to that. Nothing comes to mind immediately.

Right, I understand not breaking people's existing installs. Maybe Anope reads from install base first, then if it doesn't see the file reads from confdir. People on a packaged install would likely place their key in /etc/anope/ which is the confdir. It could be dbdir instead. I'm not opposed to either. As long as it's a directory Anope knows about from the passed flags.

**Comment by SadieCat** [comment]
The way paths are handled currently isn't great and I want to improve it for 2.1.

For now though I think the "services directory" on Debian is `/usr`.
