### ISSUE TITLE
ns_no_expire has no effect in nickserv defaults

### ISSUE THREAD

**Issue by GTAXL** [anope/anope#350]
Hello, I run Anope 2.0.12 from Debian. I want to setup Anope so nicks don't expire by default. In the nickserv.conf it lists `ns_no_expire` as an option for defaults. I set it there, yet it seems to have no effect. Newly registered nicks still show an expire date and when I do a NickServ LIST there is no !, which indicates a no-expire nick. I also do a NickServ INFO and don't see no expire in options either. I use SQL as the database backend. PeGaSuS tested it on his server and had the same result, no effect.

**Comment by SadieCat** [comment]
It seems like `NS_NO_EXPIRE` has to be set on a NickAlias rather than a NickCore. I'll revert it being documented for now and will revisit for 2.1 where I can make potentially breaking changes.

For now you can replicate more or less the same behaviour by setting `chanserv:expire` to 0.
