### ISSUE TITLE
Reason for kicks with %s instead of reason

### ISSUE THREAD

**Issue by Madriix** [anope/anope#354]
hi, 

Since the update to Anope 2.1.2, the chanserv/botserv robots automatically kick with this reason by putting "%s" in place of the reason: 

> Coeurdecristal was kicked by NanDeZeus (services@services.xxcom) ( Reason: %s).

Perhaps because of a French translation which confuses reason?

Regards

**Comment by SadieCat** [comment]
What command was used to initiate this kick?

**Comment by Madriix** [comment]
@SadieCat These are auto kicks generated by `/bs help kick` such as `"[18:04:52] J1xxxxx kicked from #xxxx by NanDeZeus: Surveillez votre langage !"`. The line I just showed you is dated 3 days ago, it was version 2.1.1

**Comment by SadieCat** [comment]
Can you check if this happens on 2.1.2 or the latest 2.1 git? I think I might have fixed this already in an unrelated commit.

**Comment by Madriix** [comment]
@SadieCat ah oops I was wrong in saying that I was under version 2.1.1. It's 2.1.2. It's quite complicated with git

**Comment by SadieCat** [comment]
Can you confirm the exact revision you're using (`git rev-parse HEAD`)? I can't replicate this at all on the latest git.

**Comment by Madriix** [comment]
I would install version 2.1.3 as soon as it becomes available because I currently have Anope 2.1.2 with the tar.gz archive. I'm not very familiar with git compared to using the archive.

**Comment by Madriix** [comment]
@SadieCat I installed Anope 2.1 via Git. It doesn't solve the issue with the %s; %s still appears in the reasons for BotServ kicks. My Anope is set to the French language.

**Comment by SadieCat** [comment]
That message shouldn't be put through the translation system so I'm not sure why it would do that. I'll look into it.

**Comment by Madriix** [comment]
Maybe it's something related here: https://github.com/anope/anope/commit/f92c5471c24253128939974327eda7db95ff06ee ?
Since it dates back a month ago and concerns the "%s", and it was working fine before the kicks on version 2.1.1.

**Comment by SadieCat** [comment]
Ah I missed that you said that this was being caused by an automatic kick. I'll push a fix shortly.

**Comment by Madriix** [comment]
@SadieCat thank you it works
