### ISSUE TITLE
Since December, I've had Anope 2.1.x, and a SASL/JOIN issue started occurring from that moment onwards.

### ISSUE THREAD

**Issue by Madriix** [anope/anope#364]
Hi there,

Since early December, I've upgraded from Anope 2.0.x to 2.1. Since then, I've been experiencing an issue with a IRC client that uses a BNC. I'm unsure whether the problem stems from the BNC, my web client, or even mIRC, or if it's related to the new Anope version.

The problem is difficult to replicate consistently; it seems to occur randomly.

Here's the symptom of the issue:

- Occasionally, after connecting via SASL following a restart of Anope 2.1 or during high MySQL overload, there's a connection issue. The connection is successful on UnrealIRCd 6.1.1.1 (I haven't changed the version for almost a year), the nickname is properly identified, and the user is connected to the joined channels. However, they appear frozen; although present in the channel, they can't see themselves or open the channel, even after restarting their IRC client. Interestingly, reconnecting from the BNC resolves the issue. However, this fix isn't always reliable; the problem reoccurs at least five times a week if the user connects at least once daily.

Is this type of symptom possible with Anope 2.1?

I would like to revert to Anope 2.0.x, but it would be quite a hassle to reinstall ./services and reconfigure the files. Therefore, I'll stick with version 2.1 for now.

Best regards,

**Comment by SadieCat** [comment]
>However, they appear frozen; although present in the channel, they can't see themselves or open the channel, even after restarting their IRC client. 

This shouldn't be something caused by services as far as I know?

**Comment by Madriix** [comment]
@SadieCat I think you can close it; it's probably a problem with the BNC server.
