### ISSUE TITLE
HostServ vhost activation Bug

### ISSUE THREAD

**Issue by fuadragon** [anope/anope#366]
**Description**

When a vhost is activated HostServ shows it twice as mentioned below in paste.

**Steps to reproduce the issue:**

1.
2.
3.

**Describe the results you received:**

https://paste.mozilla.org/u3B0oYMs 

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `services --version`:**

Anope 2.1.2

**Comment by TehPeGaSuS** [comment]
Just for some more info, from IRC:
```
<Techman> RE: HostServ duplicate messages, this happens because of synconset if you have that enabled. This is because setting vhosts exist per nickname and not at the account level, so the sync operation causes a second notice to be sent.
```
We should probably mute the `synconset`? After all, HostServ already warns us when the vHost is activated/set.
