### ISSUE TITLE
`NS LIST *` command is avaliable to any registered user

### ISSUE THREAD

**Issue by TehPeGaSuS** [anope/anope#367]
**Description**
The `/ns list *` command seems to be usable by any registered user to see the entire list of registered users.
I've added `opersonly = yes` to the `ns_list` configuration bit but that didn't change anything. It is like below:
```
module
{
	name = "ns_list"

	/*
	 * The maximum number of nicks to be returned for a NickServ LIST command.
	 */
	listmax = 50
	opersonly = yes
}
```
IMHO, having this available to any registered user is a security breach/concern.

**Steps to reproduce the issue:**

1. Connect to your network as a registered user, without any oper privileges
2. Type `/ns list *`
3. You'll be able to see ALL the network registered users

**Describe the results you received:**
Any registered user is able to use `/ns list *` and therefore see all the registered users that the network has.

**Describe the results you expected:**
Only opers should be able to see the list of registered users.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `services --version`:**
Anope-2.1.3-git (gb26f198) -- build #2, compiled 21:08:32 Feb 25 2024, flags DG

**Comment by SadieCat** [comment]
If you want to make it oper-only you need to add a permission to the `nickserv/list` command, e.g.

```
command { service = "NickServ"; name = "LIST"; command = "nickserv/list"; permission = "nickserv/list" }
```
