### ISSUE TITLE
ChanServ Kick Msg on SUSPEND

### ISSUE THREAD

**Issue by fuadragon** [anope/anope#372]
**Description**

When a user in channel, and you as root administrator use /cs suspend #channel +time reason -> chanserv kicks like -->  * You were kicked from #f by ChanServ (%s)

**Why this would be useful**

I would suggest to replace the first kick text (when user/users in the channel) this -> (%s) , with something like this -> ( This channel has been suspended by NetworkName Administration ) as an example.

**Comment by fuadragon** [comment]
https://paste.mozilla.org/XeQtVvak

**Comment by TehPeGaSuS** [comment]
Issue confirmed on my network running `Anope-2.1.4-git (g08a3523) -- build #6, compiled 02:11:22 Mar  5 2024, flags DG`

**Comment by fuadragon** [comment]
Same thing for OperServ , infor beloww in link

https://paste.mozilla.org/OEJGznTy
