### ISSUE TITLE
OperServ FORBID

### ISSUE THREAD

**Issue by fuadragon** [anope/anope#373]
**Description**
After setting /OperServ FORBID command on a channel, OperServ kicks, after trying to rejoin it sets invite mode.
After a period of time it sets -i , so user is able to try to rejoin again, and this time ChanServ kicks user.

I would suggest , it would set PERM ban in both cases ( user in channel or channel was empty ).
Instead of --> #f unable to join channel (invite only), would be nicer to set permanent ban ( instead of setting +/- invite mode) --> #f unable to join channel (Channel has been suspended. OR This channel may not be used.) In my opinion second reason would be better for OperServ FORBID, as it drops channel if it was registered.

https://paste.mozilla.org/v0PYL4Fb

Anope-2.1.4-git (g08a3523) -- (enc_sha256) -- build https://github.com/anope/anope/pull/1, compiled 17:44:32 Mar 4 2024, flags G

**Comment by SadieCat** [comment]
What IRCd is this on? Anope doesn't set the channel as invite-only it tells the IRCd to prohibit users from joining the channel.

**Comment by SadieCat** [comment]
Ah I see. Your IRCd doesn't support sqlining channels so its holding the channel instead.

What do you have `chanserv:inhabit` set to? The channel shouldn't be in this state for more than 15 seconds by default.

**Comment by fuadragon** [comment]
> Ah I see. Your IRCd doesn't support sqlining channels so its holding the channel instead.
> 
> What do you have `chanserv:inhabit` set to? The channel shouldn't be in this state for more than 15 seconds by default.

I'm using InspIRCd-3.17.0
inhabit = 15s
Thats my point is, its better to set perm ban, instead of (invite only), otherwise it can continue forever, if some stubborn will continue "play" with services.

**Comment by SadieCat** [comment]
If you load the cban module onto InspIRCd this should stop happening.

**Comment by fuadragon** [comment]
> If you load the cban module onto InspIRCd this should stop happening.

same logic as with chanserv suspend, where services dont set perm ban, only +i mode, which takes down after some time, so people can keep joining and get just a kick.   and if nickname got suspended, thats it, finita la comedia. no one can take it, services should send a message to one who types /nick suspendedNickname, hey you know, its suspended, choose another one. otherwise this can continue forever

**Comment by fuadragon** [comment]
> If you load the cban module onto InspIRCd this should stop happening.

+ I already have that module loaded.

**Comment by SadieCat** [comment]
On InspIRCd v3 you may also need to set `<cban glob="yes">`, rehash, and relink services.

**Comment by fuadragon** [comment]
I have it set as  <cban glob="yes">  , rehashed many times, shutdown few times since yesterday, relinked back.

https://paste.mozilla.org/kgW2kGs8  -> this can last forever every 15s, thats my point. Im just reporting what i see :)
wont bother anymore.

**Comment by SadieCat** [comment]
Oh wait a minute I see whats up here.

**Comment by fuadragon** [comment]
> Oh wait a minute I see whats up here.

CBAN by itself works pretty well.  If you mentioned about CBAN then it means OS FORBID should work with CBAN. But  It seems  /OperServ Forbid doesnt work with CBAN.
