### ISSUE TITLE
/OS Forbid and /OS Sqline Issues

### ISSUE THREAD

**Issue by fuadragon** [anope/anope#384]
**Description**
/OperServ FORBID with +5m expiration time wont expire. It keeps forever channel Cbaned and releases every 1 minute ( inhabit time ), then kicks again. 

/OperServ SQLINE with +5m expiration time expires on a time, when time is expires and you want to join a channel operServ KILLS you from a server. 

SQLINE didnt respect inhabit(1m), it kept channel Cbaned till the end without inhabit time. Thats what i wish to be added to forbid too.

When you add SQLINE with time, it doesnt show a time when its gonna expire, but FORBID does and KILLS a user at the end on a given time, when a user joins a channel.

**Steps to reproduce the issue:**

1. Link for FORBID  -->  https://paste.mozilla.org/TegyJtae
2.
3. Links for SQLINE --> https://paste.mozilla.org/XjPQqumc

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `services --version`:**

Anope-2.1.4-git (ge2df7d4)  InspIRCd 3+ -- (enc_sha2) -- build #1, compiled 23:36:53 Mar 11 2024, flags G

**Comment by SadieCat** [comment]
Forbid expiration is fixed in commit [7d7664444a8b91ecde082fd56e37cfef8090e72c](https://github.com/anope/anope/commit/7d7664444a8b91ecde082fd56e37cfef8090e72c). In the future please file one issue for each issue as its hard to track stuff if you file one issue for multiple issues.

**Comment by fuadragon** [comment]
> Forbid expiration is fixed in commit [7d7664444a8b91ecde082fd56e37cfef8090e72c](https://github.com/anope/anope/commit/7d7664444a8b91ecde082fd56e37cfef8090e72c). In the future please file one issue for each issue as its hard to track stuff if you file one issue for multiple issues.

Sure, i will do seperate issues for each problem.
