### ISSUE TITLE
Since updating to Anope 2.1.4, it now requires confirming a captcha to delete a user account, which is inconvenient.

### ISSUE THREAD

**Issue by Madriix** [anope/anope#392]
Since updating to Anope 2.1.4, I've encountered an issue with my Geo/IRCop bot. It needs to perform certain tasks automatically, including closing user accounts using the command /ns drop [username]. However, it's no longer possible to do so without confirming a captcha. How can I disable this captcha requirement or adjust the settings accordingly? Best regards

**Comment by SadieCat** [comment]
This isn't a captcha. Its a confirmation code. Its supposed to be inconvenient by design so to stop users from accidentally dropping the wrong nickname.

**Comment by SadieCat** [comment]
Now that I think about this a bit more we can probably add an oper privilege to override drop codes and document that it generally shouldn't be used.

**Comment by SadieCat** [comment]
You can now give your bot the chanserv/drop/override and nickserv/drop/override privs and use `OVERRIDE` as a drop key to intentionally override confirmation codes.

**Comment by Madriix** [comment]
@SadieCat I've implemented the two modifications in cs_drop.c and ns_drop.c, as well as the two lines in anope.conf, so it works well now when typing:

> /ns drop testy override

But in your code, it indicates with the "||" that it should also work without adding "override," but I can't get it to work. Should it work?

**Comment by SadieCat** [comment]
That's not the case. You can either specify a drop code as a regular user or use `OVERRIDE` as the drop code if you have the oper priv.

**Comment by Madriix** [comment]
@SadieCat Ah, I'm going to use `/ns drop <nick> OVERRIDE`, it has already been placed in my main scripts
