### ISSUE TITLE
Services crashing setting channel modes

### ISSUE THREAD

**Issue by Rezzy08** [anope/anope#394]
**Description**
(this is running on Windows, haven't tried this on my linux box yet)
When setting any channel mode (+O, +m, +i, etc..) services crash with Protocol error: Invalid timestamp

**Steps to reproduce the issue:**

1. Fresh install and configuration of UnealIRCD 6.1.4 + Anope 2.1.4

2.  connect to your server and join a channel (identifying to a registerd nick or opering has no effect on this bug you just need to be able to set modes on a channel)

3. set any channel mode (like +m for example)

**Describe the results you received:**
[11:46] -irc.wayuseless.com- link.LINK_ERROR_MESSAGE [error] Error from services.wayuseless.com: Invalid timestamp: +m
[11:46] -irc.wayuseless.com- link.SQUIT [info] SQUIT: Forced server disconnect of services.wayuseless.com by services.wayuseless.com (Protocol error: Invalid timestamp: +m)
[11:46] -irc.wayuseless.com- link.LINK_DISCONNECTED [error] Lost server link to services.wayuseless.com [127.0.0.1]: Protocol error: Invalid timestamp: +m

**Describe the results you expected:**
I wasn't expecting the services to crash. I know 2.1.4 is still in development and there is going to be bugs
but the anope team can't fix the issues they don't know about 

**Additional information you deem important (e.g. issue happens only occasionally):**

[ircd.log](https://github.com/anope/anope/files/14948746/ircd.log)
[services.log](https://github.com/anope/anope/files/14948747/services.log)

**Output of `services --version`:**
Anope-2.1.4 -- build #1, compiled 12:28:49 Apr  1 2024, flags W

**Comment by SadieCat** [comment]
This has already been fixed in git.

https://github.com/anope/anope/commit/e0a6f7456b58fa38e1d8f3b34a7aa50035650de6
