### ISSUE TITLE
Global `global` command just send the first word of a message

### ISSUE THREAD

**Issue by TehPeGaSuS** [anope/anope#397]
**Description**
When using `/msg Global global This is a message`, only the word `This` will be sent to the users.

**Steps to reproduce the issue:**

1. Type `/msg Global global This is a message` and send it
2. The users will only receive the word `This` as a global message

**Describe the results you received:**
Same as in the description

**Describe the results you expected:**
Users should receive the entirity of the message.

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happens always

**Output of `services --version`:**
Anope-2.1.5-git (5473311) -- build #1, compiled 19:08:55 Apr 22 2024, flags DG

**Comment by SadieCat** [comment]
This also applies to global/server. The maximum number of parameters needs to be set to 1 and 2 respectively.

**Comment by SadieCat** [comment]
Fixed in https://github.com/anope/anope/commit/1647968c5083ae41ebaac259bddc83b27300830f
