### ISSUE TITLE
[Anope 2.1] An unusual bug with modes using "/cs mode"

### ISSUE THREAD

**Issue by Madriix** [anope/anope#406]
For the past few days, I have tried to apply "`/cs mode #channel LOCK add +H 10:120`" on several channels, but it doesn't execute, not even with "`/cs mode #channel SET +H 10:120`".

Yesterday, I created a new channel and typed "`/cs mode #channel LOCK add +H 10:120`", but it didn't apply either.

I didn't have this bug on Anope 2.0. Are you also experiencing this issue?

**Comment by SadieCat** [comment]
Can you start with `--support` and pastebin a log of adding a mode lock?

**Comment by SadieCat** [comment]
I think I've found the cause. Can you check whether the latest 2.1 git works for you?
