### ISSUE TITLE
Hide services server name on /VERSION requests

### ISSUE THREAD

**Issue by TehPeGaSuS** [anope/anope#424]
**Description**

Some IRCds, such as UnrealIRCd and InspIRCd allow us to configure them in a way that we can hide the name of the services server from /LINKS and /MAP commands.
Unfortunately, if we do `/QUOTE VERSION NickServ` or `/CTCP NickServ version`, as example, the reply from Anope will include the server.
Here's version reply example from WeeChat, after a `/CTCP NickServ version`:
```
-- CTCP reply from NickServ: VERSION Anope-2.1.8-git (aa0496f) services.example.com :UnrealIRCd 4+ - (enc_argon2) -- build #1, compiled 19:28:16 Aug  9 2024, flags DG
```
It would be very handy if we could hide the services server name and make the reply to be something like:
```
-- CTCP reply from NickServ: VERSION Anope-2.1.8-git (aa0496f) :UnrealIRCd 4+ - (enc_argon2) -- build #1, compiled 19:28:16 Aug  9 2024, flags DG
```
Note: the complete output should always be shown to opers.

**Why this would be useful**
This will help to somewhat mitigate possible attack vectors for those who have the service server accessible from the outside.

**Comment by SadieCat** [comment]
I've removed the server name entirely from the CTCP version output as its not really useful there. On InspIRCd v4 the server version will already be hidden if you have `<security:hideserver>` enabled. I'll need to check how other IRC servers handle hiding server names.
