### ISSUE TITLE
TLS fingerprint login not throwing 900

### ISSUE THREAD

**Issue by incorrigo** [anope/anope#425]
**Description**
Not sure if this is an unreal issue or an anope issue. My apologies if it is the former

**Steps to reproduce the issue:**

1. have an account with registered nickname(s)
2. associate a TLS certificate for certfp on the cert list of that account
3. connect with (a) that valid TLS certificate (b) not using a nickname in the group of that account's nicknames

**Describe the results you received:**
nickserv _does_ say SSL certificate fingerprint accepted, you are now logged in as <main account nick>.
but the raw 900 message does not occur alongside it

**Describe the results you expected:**
in every other circumstance, a 900 message confirms that you are now logged in as <account name>
but if you are not using a nickname in <account>'s group, it doesn't

**Additional information you deem important (e.g. issue happens only occasionally):**
i'm making a script just for my network to encourage new users the opportunity to start using a real IRC client
the 900 message gives a confirmation of a login - i have come to rely on this when validating / enabling functionality that requires the user to be logged into an account. it is more reliable than +r and this is just one hole that i found

the stable release of anope has always done exactly what it says on the tin, and i don't mean any disrespect reporting what is just this one error in what is otherwise a harmony of SQL powered dependable functionality </bumlick>

**Output of `services --version`:**

```
[19:40] -nickserv- **[unregistered nickname welcome message]**
hello vicky-p3. welcome to incorrigo syx. why not create an account with us? for more info: /query nickserv help
-
[19:40] -network- **[logonnews]**
[Logon News - Jun 21 18:52:50 2024 UTC] 4,4:4,1westid.4,4:0,4official youtube channel channel4,4::0,4-->4,4 #14,1incorrigo15,1syx
[19:40] -network- [Logon News - Jul 18 15:59:09 2024 UTC] 4network: all servers have been upgraded to v6.1.7.1
-
[19:40] -hostserv- **[vhost activated]**
Your vhost of lH-4B6N128X.millions.incorrigo.com is now activated.

[19:43] * Host / IP: [lH-4B6N128X.millions.incorrigo.com] is now your displayed host
-
**[services notice but no 900 message]**
[19:40] -nickserv- SSL certificate fingerprint accepted, you are now identified to vicky-p.
```

**Comment by SadieCat** [comment]
I think this is probably an UnrealIRCd issue? Services doesn't send that numeric the IRCd does.

**Comment by incorrigo** [comment]
my network is like a toy train set to me, so i discover obscure nuances like this, sorry to be a nu[is]ance

**Comment by incorrigo** [comment]
i have raised this with unrealircd

hope this helps
