### ISSUE TITLE
problem anope_geoip_country empty

### ISSUE THREAD

**Issue by Ircgo** [anope/anope#430]
Downloading...
   Country Database:      Done
Unpacking...
unzip:  cannot find or open GeoIPCountryCSV.zip, GeoIPCountryCSV.zip.zip or GeoIPCountryCSV.zip.ZIP.
rm: cannot remove 'GeoIPCountryCSV.zip': No such file or directory
Converting to UTF-8...
iconv: cannot open input file `GeoIPCountryWhois.csv': No such file or directory
rm: cannot remove 'GeoIPCountryWhois.csv': No such file or directory
Importing...
mysqlimport: [Warning] Using a password on the command line interface can be insecure.
mysqlimport: Error: 3948, Loading local data is disabled; this must be enabled on both the client and server sides, when using table: anope_geoip_country
rm: cannot remove 'anope_geoip_country.csv': No such file or directory
rm: cannot remove 'anope_geoip_country6.csv': No such file or directory
Done...

**Comment by SadieCat** [comment]
Unfortunately the GeoLite1 databases are no longer provided by MaxMind. I'm working on a replacement that uses GeoLite2.

**Comment by Ircgo** [comment]
Thankyou sadiecat

**Comment by SadieCat** [comment]
To avoid breaking 2.0 I've switched this to a mirror in bafcba0 and have opened #433 to track moving 2.1 to use GeoLite2.
