### ISSUE TITLE
Extended bans : The letters are considered in /cs mode, but not the names

### ISSUE THREAD

**Issue by Madriix** [anope/anope#431]
By following this documentation: https://www.unrealircd.org/docs/Extended_bans, 
there is a possibility to execute letters like `~C:` with `/cs mode`, and this works correctly. However, it doesn't work when using names like `~country:`.

Non-functional example:
`/cs mode #test set +b ~country:FR`

Functional example:
`/cs mode #test set +b ~C:FR`

I am using the latest version of Anope (2.1.8).

**Comment by SadieCat** [comment]
Anope does not support NEXTBANS on UnrealIRCd currently. I'm open to adding support in 2.1 if someone is willing to help with testing.

**Comment by TehPeGaSuS** [comment]
Sure. Count me in for the testing.

**Comment by SadieCat** [comment]
I've implemented this. Please test if you are able.

**Comment by Madriix** [comment]
@SadieCat 
`modules/protocol/unrealircd.cpp`
Do I just need to copy this file and recompile to test?

**Comment by SadieCat** [comment]
Its probably better if you clone the latest 2.1 Git rather than just update the protocol module source file.

**Comment by Madriix** [comment]
@SadieCat I updated to version 2.1.10, and it’s working well, thank you. Sorry, I couldn’t install the git version before; it takes a bit of time to set up and then revert back to the old one
