### ISSUE TITLE
~a:account doesn't affect anyone if it is not the main in their [target's] group on list modes

### ISSUE THREAD

**Issue by incorrigo** [anope/anope#434]
**Description**
using the account selector in a ban, exception, or invite needs to be the main nickname of the account of the user and not the one which they are currently using

i stood by and watched the ~a: / ~account: thing because i assumed someone woulf have noticed. so i thought i'd mention this one because i couldn't find a way to script the main account of the user without introducing a race condition by way of results of a lookup

**Steps to reproduce the issue:**

1 (i). /register |2a$$\\'0RdZ© banned@incorrigo.io
1 (ii). /nickserv CONFIRM [confirmation code]
2. /nick irritablebowel
3. switch to *channel operator's perspective*
4. /chanserv mode #syndrome lock add +b ~a:irritable_bowel
5. switch back to irritablebowel
6. /hop
7. * irritablebowel has left #syndrome
8. * irritablebowel has joined #syndrome
9. LUK AT THE PENIS ON MY HEAD 8==========D LOVE FROM EFNET

**Describe the results you received:**
* irritablebowel has joined #syndrome
<irritablebowel> LUK AT THE PENIS ON MY HEAD 8==========D LOVE FROM EFNET

**Describe the results you expected:**
**banned:** You were all banned by westid [reason: banned]

**Additional information you deem important (e.g. issue happens only occasionally):**
applies to all three list modes. guest list can't get past invite only. nuisance to be banned still swans in like they own the place. exceptions still getting marginalised by sweeping bans that should not apply to them

**Output of `services --version`:**
./services --version
Anope-2.0.16 -- build #1, compiled 03:02:25 Aug  3 2024

**Comment by SadieCat** [comment]
Extended bans are implemented by your IRC server not by Anope. I'm not sure UnrealIRCd (guessing from your extban syntax) has the information available to apply bans to grouped nicknames as well as account names.

**Comment by incorrigo** [comment]
my sincere apologies, it didn't look very clear where i ought to have reported this issue. but your answer does bring up a couple of points of intrigue

could there be some kind of JSON / @-tags thing for things like this

i use the mysql database in my anope config, which is brilliant never had an issue in 5 years, and keep the most recent *stable release* anope running and unreal 6.1.8 on my network

i've not checked if there are v3 message tags / JSON logging between servers, but could some vendor specific information - not saying client to client, just because as far as i'm concerned the services database can rinse any of these problems away?

sorry for reporting in the wrong place i just thought it as too easy to side-step for seasoned spammers

**Comment by incorrigo** [comment]
**may as well:** i was going to ask if anope would be able to support unreal's $standard £variables

**Comment by SadieCat** [comment]
If UnrealIRCd exposed an interface for communicating grouped nicknames then we could add support. We already do this on InspIRCd with the accountnicks metadata.
