### ISSUE TITLE
Anope won't work with MySQL 9.0 or later as a database.

### ISSUE THREAD

**Issue by abcbarryn** [anope/anope#436]
**Description**
When connecting to MySQL databases, Anope tries to use the mysql_native_password authentication method, this was deprecated in MySQL version 8 and removed in MySQL 9.x and later.

**Steps to reproduce the issue:**

1. Install Anope
2. Install MySQL version 9.0 or later
3. Configure Anope to connect to the MySQL database

**Describe the results you received:**
MySQL: Unable to connect to MySQL service mysql/main: Authentication plugin 'mysql_native_password' cannot be loaded: /usr/local/mysql/lib/plugin/mysql_native_password.so: cannot open shared object file: No such file or directory

**Describe the results you expected:**
Successful database connection.

**Additional information you deem important (e.g. issue happens only occasionally):**
100% reproduceable.

**Output of `services --version`:**
Anope 2.0.16, build #1, compiled 13:51:32 Oct 21 2024

**Comment by SadieCat** [comment]
Anope does not load MySQL plugins. This is an error from your MySQL client library.

**Comment by abcbarryn** [comment]
I found the problem, the problem is my database is actually MariaDB. MariaDB latest version still uses the mysql_native_password method as default, but MySQL removed this method in version 9 AND Anope will not build against or detect the MariaDB client library. Building Anope using the slightly older 8.4.3 MySQL library works however to connect to MariaDB. It would be nice f the MariaDB client library was supported in addition to MySQL.

**Comment by SadieCat** [comment]
Building against the MariaDB client library *is* supported. Our CI builds against MariaDB and it works fine. You just need to install the relevant compatibility libraries from your package manager.

**Comment by abcbarryn** [comment]
Hmmm, well, I have 10.11.2-MariaDB with the dev packages installed and I have linked other apps against MariaDB but Anope's Cmake gave an error saying it couldn't find libmysqlclient on my system, which is part of MySQL and is not included in MariaDB.

I have these MariaDB packages installed...
```
mariadb-errormessages-10.11.2-158.noarch
mariadb-rpm-macros-10.11.2-158.x86_64
mariadb-client-10.11.2-158.x86_64
libmariadbd19-10.11.2-158.x86_64
libmariadbd-devel-10.11.2-158.x86_64
mariadb-test-10.11.2-158.x86_64
mariadb-10.11.2-158.x86_64
mariadb-bench-10.11.2-158.x86_64
mariadb-tools-10.11.2-158.x86_64
```

**Comment by Techman** [comment]
What happens when you have `libmariadb-dev-compat` installed as well?

**Comment by abcbarryn** [comment]
I don't think that package was not one of the ones my MariaDB built. Let me see if I can find and add it.
