### ISSUE TITLE
Coredump on FreeBSD due to anope.conf misconfiguration

### ISSUE THREAD

**Issue by devnull-hub-lab** [anope/anope#443]
Hi, 

Just curiosity, on FreeBSD some anope.conf misconfiguration results in Coredump instead of showing the error or nicely message.

Example:
In anope.conf, I did the wrong configuration:
pid = "data/anope.pid"       #anope is already in data directory, so data/data/ directory doesn't exist

When I run:

$ ./anope/bin/anope
Anope 2.1.10, build #1, compiled 13:56:11 Nov  5 2024
Using configuration file conf/anope.conf
$ dmesg
pid 61589 (conftest), jid 9, uid 0: exited on signal 11 (core dumped)

To see what caused the coredump, I need to check services.log ou run anope with no fork (-n) option, so I got:
[Nov 05 14:11:50 2024] Can not write to PID file data/data/anope.pid

Anope is not exited nicely with stderr... or the exception is not showing something like "check services.log for more details"

I don't know if coredump is the expected behavior.

Tested on Anope 2.1.10.

Thanks,

~ devnull

**Comment by SadieCat** [comment]
Is it possible for you to start in GDB (`gdb ./anope/bin/inspircd`, then run `set solib-search-path /path/to/anope/modules` and `run -support`) and pastebin the output of `bt full` after it crashes?

**Comment by devnull-hub-lab** [comment]
Sure SadieCat!
Please give me a moment, I need to prepare a less restricted environment on FreeBSD jail to use debugging tools.
I'll get back to you as soon as it's finished.
