### ISSUE TITLE
anope_db_ChanAccess table

### ISSUE THREAD

**Issue by Madriix** [anope/anope#449]
Hello,

The anope_db_ChanAccess table it retains all old data. Is it possible to delete what is no longer accurate ?

Regards

**Comment by SadieCat** [comment]
The issue template exists for a reason. We can't help you if you don't fill it in.

**Comment by Madriix** [comment]
@SadieCat Ok, I'll fill out the new form. But I promise that when I created the post, it was the old form, not the same one as now.
