### ISSUE TITLE
[Anope 2.1.10] Column '...' cannot be null On SQL

### ISSUE THREAD

**Issue by Madriix** [anope/anope#454]
### Description

For the past two days, the anope_db_alias SQL table has not recorded any new data due to a null constraint issue. All users with aliases are unable to authenticate using sql_authentication on the alias side.

### Steps to reproduce the issue

For example, when registering a new alias, the following error will occur:

### Describe the results you received

```[Nov 13 17:59:45.144342 2024] Debug: Error executing query INSERT INTO `anope_db_NickAlias` (`id`,`NS_NO_EXPIRE`,`last_quit`,`last_realhost`,`last_realname`,`last_seen`,`last_usermask`,`nc`,`nick`,`time_registered`,`vhost_creator`,`vhost_host`,`vhost_ident`,`vhost_time`) VALUES (0,NULL,NULL,NULL,'unknown',1731517183,'*@*','Glow','testy',1731517183,NULL,NULL,NULL,NULL) ON DUPLICATE KEY UPDATE `NS_NO_EXPIRE`=VALUES(`NS_NO_EXPIRE`),`last_quit`=VALUES(`last_quit`),`last_realhost`=VALUES(`last_realhost`),`last_realname`=VALUES(`last_realname`),`last_seen`=VALUES(`last_seen`),`last_usermask`=VALUES(`last_usermask`),`nc`=VALUES(`nc`),`nick`=VALUES(`nick`),`time_registered`=VALUES(`time_registered`),`vhost_creator`=VALUES(`vhost_creator`),`vhost_host`=VALUES(`vhost_host`),`vhost_ident`=VALUES(`vhost_ident`),`vhost_time`=VALUES(`vhost_time`): Column 'NS_NO_EXPIRE' cannot be null```

### Describe the results you expected

It should register correctly, and then this table might function as expected. There is also a similar issue with another table named anope_db_ChannelInfo, as follows:

```
[Nov 13 17:36:22.200798 2024] Debug: Error executing query INSERT INTO `anope_db_ChannelInfo` (`id`,`BS_FANTASY`,`BS_GREET`,`CS_NO_EXPIRE`,`CS_STATS` ...) Column 'BS_GREET' cannot be null
```

At the end of this topic, I discuss it: https://github.com/anope/anope/issues/451

### Anope version

2.1.10

**Comment by SadieCat** [comment]
Would it be possible for you post the output of `DESCRIBE anope_db_NickAlias;`.

**Comment by Madriix** [comment]
@SadieCat Yes

![Sans titre-2](https://github.com/user-attachments/assets/ab09eb6d-daeb-425c-8c77-d2df8bda9be1)

**Comment by SadieCat** [comment]
Ignore my previous now-deleted post. This should be fixed in the latest 2.1 git. You will need to recreate your tables for this fix to work though (either export your SQL data and reimport with the new schema or re-import from your flatfile database).

**Comment by Madriix** [comment]
@SadieCat I imported the "mysql.cpp" file, it is recreating all the anope_db tables. In the anope_db_alias table, there are now 4200 aliases, it's cool, it seems to work. Afterwards, I will create an alias on a pseudo to check if it works

**Comment by Madriix** [comment]
@SadieCat The import now works well when recreating the tables, but when removing a nickname from the group or creating an alias in the group, it does not update in anope_db_alias.

**Comment by Madriix** [comment]
@SadieCat finally it works, I found the solution, it is to leave import = true; all the time in db_sql. Never disable. Now when a user deletes or adds an alias, it works fine

**Comment by Madriix** [comment]
It seems that keeping "import = true" all the time is the only way it works:

1. Delete the `anope_db_*` tables.
2. Start Anope with `import = true` (keeping `sql_live` enabled).
3. The tables will be created.
4. Do not create any groups or aliases for at least 5–10 minutes to allow Anope to fully load everything.
5. Keep Anope running without restarting it and with `import = true`.

After 10–15 minutes, creating or deleting an alias or group works fine.

However, this approach does **not** work:

1. Delete the `anope_db_*` tables.
2. Start Anope with `import = true`.
3. The tables will be created.
4. Avoid creating groups or aliases during Anope’s loading process.
5. Shut down Anope and set `import = false`.
6. Restart Anope.

With this method, creating or deleting aliases or groups doesn’t update the `anope_db_alias` table as expected. It seems like updates aren’t properly reflected, possibly due to a delay. It might be necessary to wait at least 15 minutes before creating or deleting aliases, although I haven't tested this yet.

**Comment by Madriix** [comment]
> It might be necessary to wait at least 15 minutes before creating or deleting aliases, although I haven't tested this yet.

I tested it; it really doesn’t work. You need to keep 'import' set to 'true'. It's the only solution. If there's a delay, just wait a few minutes for it to appear in the table, especially if Anope was just started.

**Comment by SadieCat** [comment]
I'm going to close this issue now as the null column issue has been resolved.
