### ISSUE TITLE
Conflict or update failure if db_sql::import is true. If false, it refuses to update the anope_db_Alias ​​table if a member registers or deletes an alias from the group

### ISSUE THREAD

**Issue by Madriix** [anope/anope#456]
### Description

This is report an issue with `import = true`, because I constantly have to keep it set to `true` to see updates from those who register aliases in their groups. No changes are applied unless `import` is set to `true`. However, keeping `import` on `true` all the time can cause significant server lag. This might be related to the lag issue reported here: https://github.com/anope/anope/issues/442 : It may not actually be due to the switch from MyISAM to InnoDB, although that might help somewhat, but it doesn’t fully resolve the issue. Last night, I noticed the lag occurred again while keeping `import` set to `true`, just after a restart of a client asking for a lot of sasl identification and causing SASL failure errors.

### Steps to reproduce the issue and the results you received

Two issues with `import`:

**Issue 1**: If we set `import` to `false`, aliases are never updated in the `anope_db_Alias` table. For example, if we delete an alias from our group or create a new alias in the group, it never appears in the `anope_db_Alias` table, even after an hour. However, if we keep `import` set to `true` all the time, it works.

**Issue 2**: If I keep `import` set to `true` all the time, restarting an IRC client with, for instance, 500 connected users causes all of them to reconnect simultaneously. This triggers a massive SASL identification process, and the server lags for at least 15 to 20 minutes, with some SASL failures. This issue does not occur if I set `import` to `false`. It may still happen, but only briefly—perhaps for a minute or just a few seconds. 

### Describe the results you expected

It must work correctly, as previously mentioned.
**Note**: Issue 2 would be resolved if Issue 1 were fixed.

### Anope version

2.1.10

**Comment by Madriix** [comment]
I just tested it. Anope has been running since last night with `import = false`, and when I create an alias in a group, it does appear in the `anope_db_Alias` table. It seems that during the first few hours after Anope starts, it doesn't work. You have to wait 1 hour, 6 hours, or 12 hours—I’m not sure. Where could this problem be coming from?

**Comment by Madriix** [comment]
I'm testing again currently:

1. Anope has been stopped, and I set `import = true` again.
2. I deleted the tables `anope_db_*`.
3. Anope is currently recreating them (I believe it will be successful). We just need to wait for 5-7 minutes.

Next steps (waiting for completion):
- Stop Anope, but not immediately. I would say 2 or 3 minutes after it connects to IRC.
- Set `import = false` again.
- Create a new alias in a group (and wait; I’m not sure how long it will take. If it's created, I'm unsure how long it will appear in the `anope_db_Alias` table).

**Comment by SadieCat** [comment]
The db_sql module is not a live SQL module and will not immediately update your database thats what db_sql_live is for.

You will probably get weird behaviour if you keep the import setting enabled after importing from a flatfile database. The purpose of the import setting is to import data from a flatfile database when migrating to SQL. After importing you should turn it off.

You can load db_flatfile *after* db_sql if you want to keep writing a flatfile database whilst using db_sql as your primary database.

**Comment by Madriix** [comment]
@SadieCat I just put on `db_sql_live`, it still hasn't created the alias that I just created in the `anope_db_Alias` ​​table, maybe I have to wait several minutes, or 1h or 6h, or 12h, I don't know I'll see

**Comment by SadieCat** [comment]
I assume you mean anope_db_NickAlias? Did you give it a correct timestamp? Anope uses the timestamp column to discover new rows.

**Comment by Madriix** [comment]
Ah yes, anope_db_NickAlias, yes this is the right table. Are you talking about the Debian dedicated server timestamp or Anope? or others? How to check?

**Comment by Madriix** [comment]
The alias has still not been created in `anope_db_NickAlias`, and there is still no trace of it, both with the nick and nc.

**Comment by SadieCat** [comment]
There is a timestamp column in the database table that is set to the time the row was last altered (or null if it is pending deletion). You need to make sure this column is set to the current time when you insert the row.

If your clocks are out of sync you may encounter trouble with Anope picking up records so it is good practice to install a NTP client on both your services and database server.

**Comment by Madriix** [comment]
With the `Glow` user, I created an alias named "`testy`". The line was not created in the `anope_db_NickAlias` ​​table. On the other hand, for `Glow` there is a timestamp which is "`2024-11-15 15:20:06`", it is the last connection on IRC I think.

I just downloaded the file "`anope.db`" and in it "testy" appears well:

OBJECT NickAlias
DATA nick testyy
DATA last_quit 
DATA last_realname unknown
DATA last_usermask *@*
DATA last_realhost 
DATA time_registered 1731681828
DATA last_seen 1731681828
DATA nc Glow
END

but it does not appear in the sql table `anope_db_NickAlias`. With an NTP client would it work? I have never tested the NTP thing, I do not know what it is

**Comment by Madriix** [comment]
@SadieCat 
I typed this on Debian:

```
debian@ns:~$ date
ven. 15 nov. 2024 16:06:40 CET
debian@ns:~$ timedatectl
               Local time: ven. 2024-11-15 16:07:40 CET
           Universal time: ven. 2024-11-15 15:07:40 UTC
                 RTC time: ven. 2024-11-15 15:07:40
                Time zone: Europe/Paris (CET, +0100)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
debian@ns:~$
```
Everything seems normal, the date is correct, and NTP is active as indicated.

The user is created via the `sql_authentication` module. The alias (group) is created with a module called ns_sagroup.cpp using a simple command: `/ns sagroup nick target`.

The configuration I need to show is the one in anope.conf ?

**Comment by SadieCat** [comment]
>The configuration I need to show is the one in anope.conf ?

Yes.

**Comment by Madriix** [comment]
@SadieCat ok I still have to delete passwords, and sensitive stuff first, I'll come back and write in 5-10 minutes

**Comment by Madriix** [comment]
@SadieCat here is the ns_sagroup: https://gitgud.malvager.net/Wazakindjes/muhanope/src/branch/master/a2/ns_sagroup.cpp
I'm posting the anope.conf, in about 10 minutes

**Comment by SadieCat** [comment]
> You can load db_flatfile _after_ db_sql if you want to keep writing a flatfile database whilst using db_sql as your primary database.

Does it work if you do this (the same applies for db_sql and db_sql_live).

**Comment by Madriix** [comment]
@SadieCat yes it seems to work

**Comment by Madriix** [comment]
@SadieCat I will do it again as before, put the flatfile block back in front of dq_sql(live) and delete the anope_db_* tables and do everything again, I will start all over again to see if it works. Then do as now

**Comment by Madriix** [comment]
@SadieCat Ah yes, it works well. Before this month I did not know the technique to reverse the flatfile block after db_sql(live), it is good, but not practical, you have to memorize it well to remember it later. Thanks for the help

**Comment by SadieCat** [comment]
It is documented but the documentation could be clearer. I'll update it a bit.
